Add Video Stream and Data Channel Nodes
introlab/opentera-webrtc-teleop pull request #7
Opened 2020-11-19 15:27 UTC by GodCed

This adds two ROS nodes. One for streaming a ROS image topic to a WebRTC, the other to connect to the data channel and publish/receive data as string.

Paths to the native library are retrieved as environnement variables for now as CMake installation doesn't work, or I couldn't get it to work...

2020-11-19 16:07 UTC, mamaheux requested changes
J'ajouterais un binding python pour StreamClient et la source vidéo.

2020-11-19 16:07 UTC, mamaheux commented on opentera_webrtc_ros/src/RosDataChannelBridge.cpp
> + */
Je déplacerais le commentaire dans le .h.

2020-11-19 16:07 UTC, mamaheux commented on opentera_webrtc_ros/src/RosDataChannelBridge.cpp
> + */
Je déplacerais le commentaire dans le .h.

2020-11-19 16:07 UTC, mamaheux commented on opentera_webrtc_ros/src/RosDataChannelBridge.cpp
> + */
Je déplacerais le commentaire dans le .h.

2020-11-19 16:07 UTC, mamaheux commented on opentera_webrtc_ros/src/RosTopicStreamer.cpp
> +    RosTopicStreamer();
Je n'aime pas l'idée d'un constructeur bloquant.

2020-11-19 16:07 UTC, mamaheux commented on opentera_webrtc_ros/src/RosDataChannelBridge.cpp
> +    RosDataChannelBridge();
Je n'aime pas l'idée d'un constructeur bloquant.

2020-11-19 16:07 UTC, mamaheux commented on opentera_webrtc_ros/src/RosTopicStreamer.cpp
> +
Je déplacerais les commentaires doxygen dans le .h.

2020-11-19 18:49 UTC, GodCed commented on opentera-webrtc-native-client/OpenteraWebrtcNativeClient/include/OpenteraWebrtcNativeClient/Handlers/VideoStreamPeerConnectionHandler.h
> +     */
Moi je dis oui. De manière réalise je pense pas que notre librairie soit tant que ça utilisée à l'externe, alors aussi bien s'y retrouver...

2020-11-19 18:51 UTC, GodCed commented on opentera-webrtc-native-client/OpenteraWebrtcNativeClient/include/OpenteraWebrtcNativeClient/RefCountedVideoSource.h
> +     */
Idem à ci-haut

2020-11-19 18:52 UTC, GodCed commented on opentera-webrtc-native-client/OpenteraWebrtcNativeClient/include/OpenteraWebrtcNativeClient/VideoStreamClient.h
> +     */
Oui je prenais de l'avance, je me disais que dans un monde idéal tout est bien documenté. Dans un monde idéal...

2020-11-19 18:52 UTC, GodCed commented on opentera-webrtc-native-client/OpenteraWebrtcNativeClient/src/Handlers/VideoStreamPeerConnectionHandler.cpp
> + */
Idem à ci-haut

2020-11-19 18:55 UTC, GodCed commented on opentera-webrtc-native-client/OpenteraWebrtcNativeClient/src/VideoStreamClient.cpp
> + */
Une raison particulière? Personnellement je les garde autant que possible dans les sources pour minimiser l'ampleur d'un rebuild pour une type dans l'optique que le header se retrouve à plus d'endroits et que les IDE pick up les commentaires n'importe où anyway...

2020-11-19 18:56 UTC, GodCed commented on opentera-webrtc-native-client/OpenteraWebrtcNativeClient/src/VideoStreamClient.cpp
> + */
Idem à ci-haut

2020-11-19 18:57 UTC, GodCed commented on opentera-webrtc-native-client/OpenteraWebrtcNativeClient/include/OpenteraWebrtcNativeClient/VideoStreamClient.h
> +        VideoStreamClient(const SignallingServerConfiguration& signallingServerConfiguration,
À voir si on veut deux différents ou un seul, je voyais ça dans une deuxième release puisque l'envoi était plus prioritaire pour la preuve de concept de téléopération.

2020-11-19 18:58 UTC, GodCed commented on opentera-webrtc-native-client/OpenteraWebrtcNativeClient/src/Handlers/VideoStreamPeerConnectionHandler.cpp
> + */
Idem

2020-11-19 18:59 UTC, GodCed commented on opentera_webrtc_ros/include/RosDataChannelBridge.h
> +//
Ouais l'IDE a mis ça mais ça sert effectivement pas à grand chose.

2020-11-19 19:03 UTC, GodCed commented on opentera_webrtc_ros/src/RosSignalingServerConfiguration.cpp
> + */
Idem aux autres emplacements de doxygen.

2020-11-19 19:03 UTC, GodCed commented on opentera_webrtc_ros/src/RosDataChannelBridge.cpp
> + */
Idem aux autres emplacements de doxygen.

2020-11-19 19:03 UTC, GodCed commented on opentera_webrtc_ros/src/RosDataChannelBridge.cpp
> + */
Idem aux autres emplacements de doxygen.

2020-11-19 19:03 UTC, GodCed commented on opentera_webrtc_ros/src/RosDataChannelBridge.cpp
> + */
Idem aux autres emplacements de doxygen.

2020-11-19 19:03 UTC, GodCed commented on opentera_webrtc_ros/src/RosDataChannelBridge.cpp
> + */
Idem aux autres emplacements de doxygen.

2020-11-19 19:04 UTC, GodCed commented on opentera_webrtc_ros/src/RosTopicStreamer.cpp
> +
Idem aux autres emplacements de doxygen.

2020-11-19 19:05 UTC, GodCed commented on opentera_webrtc_ros/src/RosTopicStreamer.cpp
> +    RosTopicStreamer();
En temps normal moi non plus, mais pour une implémentation de noeud ROS (où le constructeur est un main glorifié) je trouve que ça fait propre pas mal. C'est assez explicite ce que le noeud fait.

2020-11-19 19:05 UTC, GodCed commented on opentera_webrtc_ros/src/RosDataChannelBridge.cpp
> +    RosDataChannelBridge();
En temps normal moi non plus, mais pour une implémentation de noeud ROS (où le constructeur est un main glorifié) je trouve que ça fait propre pas mal. C'est assez explicite ce que le noeud fait.

2020-11-19 19:32 UTC, GodCed commented on opentera_webrtc_ros/src/RosDataChannelBridge.cpp
> +    });
Ahh ok. je pensais que c'était pour "notre" connection. Ça sert pas à grand chose de les gérer alors.

2020-11-19 19:34 UTC, GodCed commented on opentera_webrtc_ros/src/RosDataChannelBridge.cpp
> +        String msg;
J'aurais tendance à dire non pour garder le bridge le plus simple possible. Si l'expéditeur est important peut-être l'encoder dans le message lui-même? Comme ça une fois dans ROS tout le côté WebRTC est complètement abstrait.

2020-11-19 19:41 UTC, GodCed commented on opentera_webrtc_ros/include/RosVideoSource.h
> +}
Comme l'ImageSource doit gérer elle-même le ré-encodage et la mise à l'échelle c'est très "application specific" à mon avis comment tu veux faire ça. Concrètement la classe ré-implémente réellement une seule méthode, la version générique que tu mentionne c'est RefCountedVideoSource dont cette classe là hérite. Le callback que tu suggère s'appelle onFrame.

2020-11-19 19:43 UTC, GodCed commented
> J'ajouterais un binding python pour StreamClient et la source vidéo.

De mon côté je voyais ça dans une prochaine release si le besoin est.

2020-11-19 19:50 UTC, mamaheux commented on opentera_webrtc_ros/src/RosTopicStreamer.cpp
> +    RosTopicStreamer();
Mais si le constructeur est un main glorifié alors pourquoi le tout est dans une classe?

2020-11-19 19:50 UTC, mamaheux commented on opentera_webrtc_ros/src/RosDataChannelBridge.cpp
> +    RosDataChannelBridge();
Mais si le constructeur est un main glorifié alors pourquoi le tout est dans une classe?

2020-11-19 19:54 UTC, mamaheux commented on opentera-webrtc-native-client/OpenteraWebrtcNativeClient/include/OpenteraWebrtcNativeClient/Handlers/VideoStreamPeerConnectionHandler.h
> +     */
Dans une avenue de clean code, il faut limiter le nombre de commentaires pour ne pas qu'il ne devienne pas cohérent avec le code. Pour moi du code avec des petites fonctions avec des noms significatifs n'a pas besoin de commentaire doxygen.

Selon moi, les commentaires doxygen sont là pour la génération de la documentation pour une utilisation externe.

2020-11-19 19:56 UTC, mamaheux commented on opentera-webrtc-native-client/OpenteraWebrtcNativeClient/src/VideoStreamClient.cpp
> + */
C'est mieux de mettre les commentaires doxygen dans le .h, car si on distribue la lib sans les .cpp, on perd la documentation.

2020-11-19 19:57 UTC, mamaheux commented on opentera-webrtc-native-client/OpenteraWebrtcNativeClient/include/OpenteraWebrtcNativeClient/VideoStreamClient.h
> +        VideoStreamClient(const SignallingServerConfiguration& signallingServerConfiguration,
On peut mettre cette feature à une future release, mais je crois que Dominic avait déjà des cas d'utilisation.

2020-11-19 20:10 UTC, mamaheux commented on opentera_webrtc_ros/include/RosVideoSource.h
> +}
1. Dans la majorité des cas, on risque vouloir envoyer des image BGR ou RGB, donc le code de RosVideoSource::imageCallback va être dupliquer. 
2. Puisqu'on fait un wrapper de WebRTC native, il n'est pas souhaitable qu'un utilisateur de notre lib utilise une classe provenant de WebRTC native, car s'il y a une modification dans WebRTC native on va devoir modifier notre lib et tous les projet utilisant notre lib.
3. Si on fait un binding python, ça va être fatidieux de le faire si on doit binder des type de WebRTC Native, car il y a beaucoup d'héritage et de méthodes. Ça complique l'utilisation si l'utilisateur doit faire le code de conversion.

2020-11-19 20:13 UTC, mamaheux commented on opentera_webrtc_ros/src/RosDataChannelBridge.cpp
> +        String msg;
Ce n'est pas une bonne idée d'un point de vue sécurité informatique, car le client peut mentir sur son identité, tandis que le contenu de client provient du serveur.

2020-11-19 20:15 UTC, mamaheux commented
> > J'ajouterais un binding python pour StreamClient et la source vidéo.
> De mon côté je voyais ça dans une prochaine release si le besoin est.

Je crois que Dominic a un cas d'utilisation.

2020-11-19 20:27 UTC, GodCed commented on opentera_webrtc_ros/src/RosDataChannelBridge.cpp
> +    RosDataChannelBridge();
Pour avoir des variables communes aux callbacks sans mettre plein de variables globales. Mais le run avec connect et spin je pense que c'est un compromis acceptable.

2020-11-19 20:28 UTC, GodCed commented on opentera_webrtc_ros/src/RosDataChannelBridge.cpp
> +        String msg;
True that, ça va prendre un type de message ROS custom, mais c'est pas la fin du monde.

2020-11-19 20:30 UTC, GodCed commented on opentera-webrtc-native-client/OpenteraWebrtcNativeClient/src/VideoStreamClient.cpp
> + */
Mais normalement on distribue la doc avec la lib non?

2020-11-19 20:39 UTC, mamaheux commented on opentera-webrtc-native-client/OpenteraWebrtcNativeClient/include/OpenteraWebrtcNativeClient/Handlers/VideoStreamPeerConnectionHandler.h
> +     */
Puisqu'il n'y a pas de consensus fort sur internet, tu peux les laisser comme cela.

2020-11-19 20:39 UTC, mamaheux commented on opentera-webrtc-native-client/OpenteraWebrtcNativeClient/src/VideoStreamClient.cpp
> + */
Puisqu'il n'y a pas de consensus fort sur internet, tu peux les laisser comme cela.

2020-11-19 21:40 UTC, GodCed commented on opentera_webrtc_ros/include/RosVideoSource.h
> +}
![image](https://user-images.githubusercontent.com/10776995/99727426-f2f39a00-2a85-11eb-8bd6-9e3baec2fc35.png)

2020-11-20 02:36 UTC, doumdi commented on opentera-webrtc-native-client/OpenteraWebrtcNativeClient/include/OpenteraWebrtcNativeClient/VideoStreamClient.h
> +        VideoStreamClient(const SignallingServerConfiguration& signallingServerConfiguration,
Le premier cas d'utilisation c'est effectivement le streaming d'une caméra (un robot ou une caméra wifi). Le deuxième cas c'est plus comme le Beam avec la vue de la personne distante sur le UI du robot (comme le Beam).

2020-11-20 14:34 UTC, GodCed commented
Comme ce qui reste à adresser c'est des nouvelles features j'irais de l'avant avec ce merge-ci qui est suffisant pour une démo de téléopération. Ok pour vous? @doumdi @mamaheux

2020-11-20 15:05 UTC, mamaheux approved these changes

2020-11-24 13:38 UTC, merged